# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_hobby_language_skill_socialmedia_study_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='hobbies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Hobby'),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Language'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Skill'),
        ),
        migrations.AddField(
            model_name='resume',
            name='social_medias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.SocialMedia'),
        ),
        migrations.AddField(
            model_name='resume',
            name='study_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Study'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Work'),
        ),
    ]
