# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20171113_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='social_medias',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='study_history',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_history',
        ),
        migrations.AddField(
            model_name='hobby',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='language',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='skill',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='study',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='work',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
    ]
