# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20171113_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='resume',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.CharField(blank=True, help_text='Where did you study?', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='study',
            field=models.CharField(blank=True, help_text='What you studied?', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
