# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20171114_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hobbys', to='resume.Resume'),
        ),
        migrations.AlterField(
            model_name='language',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='resume.Resume'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.Resume'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialmedias', to='resume.Resume'),
        ),
        migrations.AlterField(
            model_name='study',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='resume.Resume'),
        ),
        migrations.AlterField(
            model_name='work',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='resume.Resume'),
        ),
    ]
