# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20171121_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='resume.Resume'),
        ),
    ]
