# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20171129_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('can_view_resume', 'Can view resume'),)},
        ),
    ]
