# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_person_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_active',
        ),
        migrations.AddField(
            model_name='resume',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
